### ISSUE TITLE
Listing installed plugins (Managing plugins katas)

### ISSUE THREAD

**Issue by atombrella** [praqma-training/jcasc-katas#7]
I found this small snippet on StackOverflow. It outputs all the plugins that are installed, and not just the ones listed in the `plugins.txt` file.

```groovy
  Jenkins.instance.pluginManager.plugins.each{
    plugin ->
    println ("${plugin.getShortName()}: ${plugin.getVersion()}");
  }
```

https://stackoverflow.com/questions/9815273/how-to-get-a-list-of-installed-jenkins-plugins-with-name-and-version-pair

**Comment by sofusalbertsen** [comment]
This have been merged in, right @atombrella ?

**Comment by atombrella** [comment]
Yes.
